const API_BASE_URL = "http://localhost:8085/api/v1";

//PETICIÓN GET PARA OBTENER TODOS LOS JUGADORES
export const ENDPOINT_Get_ALL_PLAYER = `${API_BASE_URL}/`;

//PETICIÓN GET PARA OBTENER TODOS LOS JUGADORES RELACIONADO A UN JUEGO Y RANKING
export const ENDPOINT_Get_ALL_GAME_RANKING = `${API_BASE_URL}/`;

//PETICIÓN POST PARA CREAR JUGADOR Y ACTUALIZAR LOS DATOS DEL MISMO
export const ENDPOINT_PLAYER_SAVE = `${API_BASE_URL}/`;