const API_BASE_URL = "http://localhost:8085/api/v1";

//PETICIÓN GET PARA OBTENER TODOS LOS JUGADORES
export const ENDPOINT_Get_ALL_PLAYER = `${API_BASE_URL}/player`;

//PETICIÓN GET PARA OBTENER TODOS LOS JUGADORES RELACIONADO A UN JUEGO Y RANKING
export const ENDPOINT_Get_ALL_GAME_RANKING = `${API_BASE_URL}/player`;

//PETICIÓN POST PARA CREAR JUGADOR Y ACTUALIZAR LOS DATOS DEL MISMO
export const ENDPOINT_PLAYER_SAVE = `${API_BASE_URL}/player/`;

//Petición POST para crear un Game
export const ENDPOINT_GAME_SAVE = `${API_BASE_URL}/game/`;